### ISSUE TITLE
Image background transparency

### ISSUE THREAD

**Issue by imtiaz-itg** [JibbyJames/data-studio-lighthouse-gauge#1]
Hi there, great visual! But there seems to be no option to make the visual transparent (the centre). Do you know if there is a way I can modify it?

Thanks
Immy

**Comment by imtiaz-itg** [comment]
Hi James,

Thanks for the quick reply. GDS still has a lot of limitations and your visualisation works a treat so good job!

Look forward to seeing what you can knock up!
Cheers
Immy

**Comment by JibbyJames** [comment]
Hi Immy,

I've made an update to the visualisation adding a few additional config options, one of which makes the gauge background transparent:

![lh-gauge-v2](https://user-images.githubusercontent.com/6009148/89736994-a00d4e00-da65-11ea-8959-5dad8bfc368b.png)

Let me know how you get on with this!

Thanks,
James

**Comment by JibbyJames** [comment]
Also worth noting that the screenshot I've included has a little bug in where the line edges don't align with their correct progress value (the start of the line should be dead centre) which was fixed before I committed the changes. This can't be avoided when using the rounded edges mode, but it isn't as noticeable, especially when using default line thickness values.

**Comment by imtiaz-itg** [comment]
Thanks James. Looking good. A question – is there a combination of settings I can use (I couldn’t figure one out) that will allow me to have the full circle displayed at all times with just an outline of the non-coloured element.

Something like this?
[Tableau Tip: How to make KPI donut charts]

Thanks,
Immy

**Comment by JibbyJames** [comment]
Not currently, but that's a good idea, so I'll see what I can do.

**Comment by JibbyJames** [comment]
Hi Immy,

Apologies for not getting to this sooner, but I've updated the opacity setting to only affect the "fill" of the inner circle. This leaves the outer ring visible still, allowing for it to now be possible to create the gauges in your link. I was able to create the below using the new config options:

![example-1](https://user-images.githubusercontent.com/6009148/94372828-f3f8f280-00f8-11eb-945e-e27cc39f0887.png)

The outer ring can be disabled separately, allowing for a completely transparent gauge background to be created still.

Going to close this issue now. Feel free to create another issue if you can think of other feature requests you'd like to see.

**Comment by MarijnVerdult** [comment]
Hi Jibby, love this visualization! In the images above, you have the little icons and description underneath the number. Can I do that from the config options or did you added extra (separate) elements to the page?

**Comment by JibbyJames** [comment]
Hi Marjin,

Thanks for the feedback! I was a bit cheeky with those and added the icons
as separate elements on top of the gauge, and lowered the metric value by
increasing the gauge height. A little hacky, but I've done much worse with
other visualisations in the past!

I'm not sure if uploading images as a config option is possible with
community visualisations, so hopefully the workaround I desribed is helpful
enough.

Thanks,
James

**Comment by MarijnVerdult** [comment]
That is absolutely perfect, who doesn't love a hacky solution? :)
