### ISSUE TITLE
Missing Data Option

### ISSUE THREAD

**Issue by cesalo** [JibbyJames/data-studio-lighthouse-gauge#12]
Is there a chance to replicate the "Missing Data" option from scorecards:

![image](https://user-images.githubusercontent.com/16859916/114264659-2645af80-99ba-11eb-8f9a-87177f2d0bbb.png)

Have some nulls and even trying to do a case or nary_max is not working and is just now showing up anything. It would be great if it could show 0 or 0% when is null or there is missing data.

**Comment by JibbyJames** [comment]
Great suggestion, will let you know once I've added it.

Thanks,
James

**Comment by JibbyJames** [comment]
Hey, I've added some missing data options now:

![missing-data](https://user-images.githubusercontent.com/6009148/125164232-1d1ad900-e189-11eb-81fd-1e862c8a22cd.png)

I thought it made sense for "Show 0" to respect the range stylings but the others to show the default colours.  You can find this setting in the Style tab towards the bottom:

![missing-data-2](https://user-images.githubusercontent.com/6009148/125164261-33c13000-e189-11eb-93f8-676041162322.png)
