### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JMOCARRO** [JibbyJames/data-studio-lighthouse-gauge#13]
James, Nice work by the way. I've been looking for a way to represent wind direction in Data Studio for a weather site I'm creating. Basically a visualization of a compass. Your lighthouse gauge seems like it could be readily modified to visualize the wind direction per the attached. Is that something you might consider undertaking?
[compass.pptx](https://github.com/JibbyJames/data-studio-lighthouse-gauge/files/6290810/compass.pptx)

**Comment by JibbyJames** [comment]
Thank you for the feedback! As you say I think it could be done, might be a
little tricky though. I'll take a look and see if it can done.

Thanks,
James

**Comment by JMOCARRO** [comment]
Thanks James!

**Comment by JibbyJames** [comment]
Hey! Sorry it's been ages, but I won't be able to add this feature, at least not to this repo as I'll be keeping this one strictly as the Lighthouse Gauge repo which is now in the Data Studio Community Gallery :)
