### ISSUE TITLE
Issue with non-zero minimum gauge value

### ISSUE THREAD

**Issue by purduejp** [JibbyJames/data-studio-lighthouse-gauge#15]
Let's say Minimum gauge value is set to 50 and Maximum gauge value to 100. If the metric value is 75, then the gauge should indicate the middle (i.e., 50% filled). But the gauge is indicating about 25%. See below:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/72704356/154571407-2330fdc7-6e0c-4b84-8f20-0ae26445402d.png">

**Comment by JibbyJames** [comment]
Hi,

Will investigate over the weekend and get back to you.

Thanks,
James

**Comment by JibbyJames** [comment]
Hey,

I think I've resolved the issue, plus fixed something else I spotted related to the min/max range values. I want to be a bit more cautious before I apply the fix to the files used in the community gallery though, so I'd appreciate it if you could first test it by using the dev build of the visualisation.

To use that, open the community visualisation gallery, then click "Build your own visualisation" shown below:

![gauge-build-your-own-vis](https://user-images.githubusercontent.com/6009148/155228867-c4eb56bf-5a91-4061-8633-46774f73cc4f.png)

Then insert "gs://jjbuckley-datastudio-dev/lighthouse-gauge" into the Manifest path field:

![gauge-manifest-path](https://user-images.githubusercontent.com/6009148/155229049-096e3995-b7aa-4697-87d9-ce1e68ff423c.png)

You should see the same icon appear as the main community visualisation, only the title will have "- Dev" at the end.

If all looks to be working for you, I'll apply the changes to the main version, after doing some more testing myself.

Thanks,
James

**Comment by purduejp** [comment]
Thanks James!  Let me try it now. Give me 10-15 minutes.

**Comment by purduejp** [comment]
Hi James. It worked!  Thanks so much!!

**Comment by JibbyJames** [comment]
That's great :) Thanks a lot for testing it so quickly, I'll apply the changes to the main visualisation now.

Thanks,
James

**Comment by JibbyJames** [comment]
Fixed in commit 1c4a6eb
