### ISSUE TITLE
Support for 5x colours?

### ISSUE THREAD

**Issue by andyevans** [JibbyJames/data-studio-lighthouse-gauge#18]
Hey @JibbyJames love this plug-in. Thanks so much for delivering it, have found it very useful.

Wondering if there’s any possibility of providing support for up to 5 colours in the dial?

**Comment by JibbyJames** [comment]
Hey Andy, thanks for the feedback!

I was thinking about how to do this but then got a little side-tracked so sorry for the delayed response! It should be possible, but unfortunately it would be quite a big change as having only three colours is hardcoded all over the place with low/mid/high variables and styles etc.

I'm not sure when I'll be able to get to making this change but I won't forget about it.
