### ISSUE TITLE
Support decimal formating

### ISSUE THREAD

**Issue by KevinJuf** [JibbyJames/data-studio-lighthouse-gauge#19]
Hi @JibbyJames, I love the visualization and appreciate your efforts! There is however one thing that might hold me from using this in all my reports and that's the fact that all data formats are based on UK decimals (so X,XXX.XX) where for us it's used the other way around in all other visualizations (so like X.XXX,XX) based on geo location.

Is it possible to create a functionality to switch decimal format? Or maybe even base this on geo location for consistancy?

**Comment by JibbyJames** [comment]
Hi Kevin,

That's a great idea, I will look into how I could implement this and keep
you updated :)

James

**Comment by JibbyJames** [comment]
Hi Kevin,

This didn't take much time at all to add ([5a73fba](https://github.com/JibbyJames/data-studio-lighthouse-gauge/commit/5a73fba403fc0388e3d2e6fabb002b5210fbfdf7)). You should now see the following option in the Style tab:

![eu-decimals-full](https://user-images.githubusercontent.com/6009148/216845517-99d65672-9713-464c-9f4d-cf90517d6d36.png)

You may need to clear your cache to get the latest version of the visualisation.

Thanks,
James
