### ISSUE TITLE
Gauge not showing

### ISSUE THREAD

**Issue by biowatch-andersnielsen** [JibbyJames/data-studio-lighthouse-gauge#20]
Also in the LIGHTHOUSE GAUGE DEMO here:
https://lookerstudio.google.com/u/0/reporting/bf0d5276-af97-4c9f-8bbe-068edbf79cbd/page/p_zjafp9c0mc

**Comment by JibbyJames** [comment]
Hi Anders,

I'm aware of the issue and will look into it today. No updates have been
made to the gauge so not sure what could have caused this.

Thanks,
James

**Comment by Evertsi** [comment]
Olá bom dia!
Aqui está do mesmo jeito, no aguardo de notícias!

**Comment by biowatch-andersnielsen** [comment]
Hi again, James.
It's working again now. Thank you very much!
Wondering what the problem was? :)

**Comment by JibbyJames** [comment]
That's great, all working for me too. I wasn't able to investigate yesterday so I actually have no idea what caused the issue. This has happened once before I think and it was something which affected all Community Visualisations from loading after Google made a change their side. Will close for now!
