### ISSUE TITLE
The connector manifest could not be retrieved or is invalid. Check the connector and try again.

### ISSUE THREAD

**Issue by natirivero** [JibbyJames/data-studio-lighthouse-gauge#22]
Hi @JibbyJames, thanks for creating this useful tool!

I would really love to be able to use it, but I'm getting an error when trying to "Test and add your community connector", please let me know if it's me that am doing something wrong, or if you can do something to fix this issue (see attachement below), many thanks in advance! 

![image](https://github.com/JibbyJames/data-studio-lighthouse-gauge/assets/66391423/b2b252cb-e33f-4f48-9975-858f9ac75814)

**Comment by JibbyJames** [comment]
Hi Natirivero,

Thanks for letting me know about the issue, I'll look into it.

This visualisation can actually be used without using that URL now, as I
submitted it to be one of the partner community visualisations. You should
see it near the bottom of the list of community visualisations. I've
attached an image of how it appears, hopefully that helps.

Thanks,
James

**Comment by natirivero** [comment]
Hi @JibbyJames, Thanks for your quick response! This is working now, I'm using Google Sheets to store Page Speed Results and your Gauge for visualizations.

Thanks,

Nat.
