### ISSUE TITLE
High Section more than 100% doesn't show

### ISSUE THREAD

**Issue by kitichai1** [JibbyJames/data-studio-lighthouse-gauge#3]
Hi 

First of all, thank you much for the nice Gauge!!
I've found out an issue when the score over 100%, it doesn't show the green color.
Is there somewhere can I do the configure to fix this?

Kind regards,
Kitichai

![image](https://user-images.githubusercontent.com/70055751/94329510-ce2ef900-ffe5-11ea-927a-1613e25931ae.png)
![image](https://user-images.githubusercontent.com/70055751/94329560-439ac980-ffe6-11ea-9fc2-8a20d5276aaa.png)

![image](https://user-images.githubusercontent.com/70055751/94329529-f0c11200-ffe5-11ea-89f9-9149a0851f4e.png)

**Comment by JibbyJames** [comment]
Hi Kitichai,

Thank you for the feedback!

I had suspected this issue may happen for gauges for fitness trackers that have figures above the goal for the day. I've added a fix where it caps the % of the progress bar to 100%. Let me know if this solves your issue.

Thanks,
James

**Comment by kitichai1** [comment]
Hi James,

Thank you. It's working perfectly now!!

Kind regards,
Kitichai
