### ISSUE TITLE
Community visualization JavaScript error

### ISSUE THREAD

**Issue by QuangTrungNguyen** [JibbyJames/data-studio-lighthouse-gauge#4]
Hi,

Thank you for creating this gauge chart! 

Today I encountered this error across all of my reports, do you know what could cause this? It was working fine as of 12 hours ago though.

```
System Error
Data Studio has encountered a system error.

Community visualization JavaScript error
```

Thanks!

**Comment by bmsknight** [comment]
Experiencing the same error.

**Comment by JibbyJames** [comment]
Hi there,

I published a new version yesterday which must have introduced this issue, apologies. Is there anything in the browser console which details what the error is?

Thanks,
James

**Comment by bmsknight** [comment]
Hi James,

Now the issue is not there when I refreshed the page everything is back to normal. Keep up the good work.

Thanks,
Madhushan

**Comment by QuangTrungNguyen** [comment]
Yes I just checked and the issue is no longer there! I will close this thread.

Thanks,
Vincent
