### ISSUE TITLE
Lost... "Community Visualizations Disabled"

### ISSUE THREAD

**Issue by jhirst22** [JibbyJames/data-studio-lighthouse-gauge#5]
Sorry if this is a really simple problem, but I'm at a lost for what to do...

Im able to get the gauge into data studio, but once it is there I am unable to edit the figure because "community visualizations disabled".

I am sure that I'm missing something obvious... any help is appreciated!

**Comment by JibbyJames** [comment]
Common problem!

You have to go to edit your data source and enable community visualisations
there. Some more info here:

https://support.google.com/datastudio/answer/7178497?hl=en

Thanks,
James

**Comment by jhirst22** [comment]
Ah, perfect. 

that solves it. Thanks for the quick response!
