### ISSUE TITLE
The number rounding

### ISSUE THREAD

**Issue by kitichai1** [JibbyJames/data-studio-lighthouse-gauge#6]
Hi,

I have a small issue with the number rounding, the Decimal Precision parameter on the style doesn't make any effect on the output. It used to work before but it just recently has this issue. Could you please kindly fix this issue. Thank you very much.

Kind regards,
Kitichai

![image](https://user-images.githubusercontent.com/70055751/97954806-1ad0d580-1dd7-11eb-9b3f-8399ef069b34.png)

![image](https://user-images.githubusercontent.com/70055751/97954785-0a205f80-1dd7-11eb-87e9-d5c85e52ce7f.png)

**Comment by JibbyJames** [comment]
Hi Kitichai,

Just added a fix for this now. Added this bug in the last update, as it was only applying the decimal precision to percentage values. Let me know if this has resolved the issue.

Thanks,
James

**Comment by kitichai1** [comment]
Hi James,

It's working well now. Thank you for the update.

Kind regards,
Kiticahi
