### ISSUE TITLE
Visualisation Still Working?

### ISSUE THREAD

**Issue by imtiaz-itg** [JibbyJames/data-studio-lighthouse-gauge#8]
Hi James,

I haven't used this visualisation for a while, but unless I'm configuring it wrong, it doesn't seem to be working?
I'm populating the gauge value as always but no chart is rendering.

Thanks
Immy

**Comment by JibbyJames** [comment]
Hi Immy,

It could be related to an issue which started when I added the option for
metrics as thresholds. I still need to fix that.

A workaround I found was to add a metric in all of the threshold values in
the Data tab, then remove them. If that doesn't work I'll spend time this
week debugging.

Thanks,
James

**Comment by imtiaz-itg** [comment]
Ah ok I’ll try. TBH I set all the min values  with random metrics to see if that would sort, let me have a go at what you’ve suggested and I’ll get back to you.
Thanks for the speedy reply!

**Comment by imtiaz-itg** [comment]
OK that’s got around it for now, thanks. Looks like there may be a refresh bug in GDS recently too which isn’t refreshing some of the native objects, just an FYI.
Thanks.

From: Imtiaz Ullah
Sent: 02 February 2021 15:27
To: JibbyJames/data-studio-lighthouse-gauge <reply@reply.github.com>; JibbyJames/data-studio-lighthouse-gauge <data-studio-lighthouse-gauge@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [JibbyJames/data-studio-lighthouse-gauge] Visualisation Still Working? (#8)

Ah ok I’ll try. TBH I set all the min values  with random metrics to see if that would sort, let me have a go at what you’ve suggested and I’ll get back to you.
Thanks for the speedy reply!

**Comment by JibbyJames** [comment]
Glad that's sorted it, and thanks for the heads up regarding that refresh
issue. Will likely spend some time fixing this issue this week.

Thanks,
James

**Comment by JibbyJames** [comment]
Hi Immy,

The most recent commit includes the latest DSCC library and correcting a config value for the metric. This was the issue I was experiencing when chart is first added to the report, which I suspected was related. I haven't been able to reproduce any similar issues since, so I'm going to close this now.

Let me know if you run into any other issues and I'll look into it again. Thanks again for your feedback.

Thanks,
James

**Comment by imtiaz-itg** [comment]
Thanks James. Your extension is superb and efforts are appreciated.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
