### ISSUE TITLE
Gauge chart does not show when the percentage value is 0

### ISSUE THREAD

**Issue by QuangTrungNguyen** [JibbyJames/data-studio-lighthouse-gauge#9]
Hi James,

I just noticed recently that when the percentage value is 0 (not null/no data), the gauge chart does not show at all. 

This wasn't an issue before and I'm not sure when this happened as I haven't checked my dashboard for a while. Do you have any idea why?

Thanks,
Vincent

**Comment by JibbyJames** [comment]
Hi Vincent,

Thanks for letting me know about this, should be a straightforward fix.
Will have a look at it this evening/weekend.

Thanks,
James

**Comment by JibbyJames** [comment]
Hi Vincent,

This was a simple fix, just had to change the following line:

`if(!metricValue){`

to the following:
  
`if(metricValue == null){`

as a value of "0" is considered false in JS, which I should have remembered! You should see the fix applied once the cache is updated for your vis whenever that may be, I'm still not 100% sure when these changes are applied when not in dev mode.

Thanks,
James
